amplitude/amplitude-browser-sdk-gtm-template

template.tpl
- feat: bump wrapper version to 3.0.1
https://www.npmjs.com/package/@amplitude/amplitude-js-gtm?activeTab=versions
While this PR bumps up the version to the latest v3.x, [with this change shipped](https://github.com/amplitude/amplitude-js-gtm/pull/10) in [amplitude-js-gtm](https://github.com/amplitude/amplitude-js-gtm).
=> feat: bump wrapper version to 3.0.1

metadata.yaml, template.tpl
Adds support for multiple instances of Amplitude SDK
* Adds a field to store instance name (optional)
* Instance name defaults to `$default_instance` if none is provided
* Passes instance name to `_amplitude` function as first argument
* Depends on https://github.com/amplitude/amplitude-js-gtm/pull/11
=> feat: accept amplitude instance names

metadata.yaml, template.tpl
A copy of this [changes](https://github.com/amplitude/amplitude-browser-sdk-gtm-template/pull/8).
Since we released during the middle, the commit hash has been messed up. So I recreate this pr.
Jira ticket: https://amplitude.atlassian.net/browse/AMP-71910
=> Fix track command to use groups properly

metadata.yaml, template.tpl
Bump up the gtm template wrapper to persist the event id.
https://cdn.jsdelivr.net/npm/@amplitude/amplitude-js-gtm@3.3.0
=> feat: bumpup the wrapper version

metadata.yaml, template.tpl
Following our discussion, we prefer to remove the `normalize` function, unless there's a specific requirement for the type. We will suggest users use a variable (data layer variable) in the documentation center if they need a specific type.
We are still keeping for fields that expect a certain type, like configurations, and timestamps, and the calls are not covered in the `switch/case` statement.
=> fix: fix the type for identify related value

metadata.yaml
Apply change of https://github.com/amplitude/amplitude-browser-sdk-gtm-template/pull/23
Copy sha from https://github.com/amplitude/amplitude-browser-sdk-gtm-template/commit/a8c3fe822f4557a44dc89a6eedb8bbeb4ebdb3a4
=> fix: default event tracking metadata

template.tpl
Add a `s` to match the config in Browser SDK `config.defaultTracking.sessions`
=> fix: det sessions

template.tpl
Fix trackingOptions and cookieOptions cannot be set in GTM template
https://amplitude.atlassian.net/browse/AMP-95226
https://amplitude.atlassian.net/browse/AMP-94578
Add two tables each for adding trackingOptions and cookieOptions under the "Configuration" table. 
GTM template has very limited UI components provided. I tried to strike a balance of keeping UI concise and requiring minimum user operations. There is another solution https://github.com/amplitude/amplitude-browser-sdk-gtm-template/issues/31 provided by our customer. But I'd like to not let customers input a Json string which is common error source. Open to discussion but I'd push harder to change my existing design unless it's huge improvement considering this PR is fixing a P1 bug. 
I tried to have unit tests for the template …
=> fix: configuration option

.github/workflows/update-metadata.yml
Add a CI file to auto commit the change of metadata needed when there is a new commit with `template.tpl` changes pushed to main to reduce the manual work to update the GTM template. 
GTM detects `metadata.yml` changes and update the template in the gallery. 
- sha: the SHA of HEAD
- changeNotes: the commit message of HEAD
I've tested it in my repo. Here is the [commit](https://github.com/Mercy811/gtm-auto-version-bump/commit/1dfe6c11f5a3ebe7ef0be41283d603994bceb6e8) the Github Action will make. 
Note that quotes in message are not supported and it causes an error like [this.](https://github.com/Mercy811/gtm-auto-version-bump/actions/runs/8383131973/job/22958243967)
=> Add update-metadata.yml

template.tpl
Related to https://github.com/amplitude/amplitude-js-gtm/pull/43
=> Bump up the SDK wrapper to fix issue of the missing events while closing the page

metadata.yaml, template.tpl
- test using the local app: 
1. the order of web attribution fires right.
2. The page counter is right.
=> Bumpup SDK version to fix web attribuiton and session start event order and page counter bug

.github/workflows/update-metadata.yml
`sed` command in github action uses `\` as the delimiter. However, while merging, it always merges from the sub-branch to the main branch, it always contains \  in the `$NEW_VERSION`, like `amplitude\subbranch`. This will cause a failure to update the metadata.yeal file.
=> fix the metadata update github action

template.tpl
Enable the possibility to choose a GTM variable to set the identify calls.
1. all key, value pair will be identify set operation
2. the Varible must be nested under the user_properties key. i.e. {user_priorities: {key: value}}. Because the user properties of `Google Tag: Event Settings` type variable, which is provided by GTM,  is under `user_properties` key. 
Related doc update:
https://github.com/amplitude/amplitude-dev-center/pull/261
=> feat: enable json object input for identify call

template.tpl
Provide 2 ways for adding Event properties.
- The original event properties go to `Event Properties Basic`
- The new object type event properties go to `Event Properties Object`
- here provide a dropdown to let customer choose their GTM variables. All variables are available, however, only the object format is allowed. 
- this event properties value will overwrite the event properties basic if there has any duplicate.
The related doc update:
https://github.com/amplitude/amplitude-dev-center/pull/261
=> feat: event properties object

.github/workflows/update-metadata.yml
It is possible to have a single release for multiple changes/PR, so make the release description a required input and use the last commit message as the default value.
=> Metadata CI Update

template.tpl
JIRA issue: https://amplitude.atlassian.net/browse/AMP-99408
Changing the original name of a field causes the original field in the tag to be missing. 
Update the key word for event properties back.
=> fix the missing event properties issue

template.tpl
href link in GTM must be start with `//`. Otherwise it will append `https://tagmanager.google.com/` in front of the link.
Like: https://tagmanager.google.com/www.docs.developers.amplitude.com/data/sources/google-tag-manager-client/#event-properties-object
=> fix example link

template.tpl
[Jira ticket
](https://amplitude.atlassian.net/browse/AMP-100448)
This PR only include the test for track, identify/groupIdentify, setGroup, revenue tags
I have created the tickets for others 
For init tag: https://amplitude.atlassian.net/browse/AMP-100449
For others tag: https://amplitude.atlassian.net/browse/AMP-100450
=> test: Add test for track, identify/groupIdentify, setGroup, revenue tags

template.tpl
Jira ticket: [AMP-104568]
This PR skips the input value of `setDeviceId` tag for `normalize()` which converts string to number and will round/truncate float. 
[AMP-104568]: https://amplitude.atlassian.net/browse/AMP-104568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: deviceId should not be number

template.tpl
- Keep the name of the existing textfield as `attributionExcludeReferrers` for backward compatibility
- Add a textfield with name `attributionExcludeReferrersRegex` to support regex exclude referrers. 
Update sdk wrapper version to 3.9.0 https://github.com/amplitude/amplitude-js-gtm/pull/51
- Assign `data.attributionExcludeReferrers` to `initOptions.defaultTracking.attribution.excludeReferrersText`
- Assign `data.attributionExcludeReferrersRegex` to `initOptions.defaultTracking.attribution.excludeReferrersRegex`
- The two exclude referrers in `initOptions` will be merged in https://github.com/amplitude/amplitude-js-gtm/pull/51
- Add tests for init tag when exclude referrers text fields are set
=> feat support excludeReferrers regex

template.tpl
Bump the wrapper version to include the fix https://github.com/amplitude/amplitude-js-gtm/pull/56
=> fix defaultTracking is false

template.tpl
[AMP-108260]
- deprecate defaultTracking with autocapture
- add support for `autocapture.elementInteractions`. UI has been reviewed by Alan https://amplitude.slack.com/archives/C05KY7C6M1B/p1725038674090919
[AMP-108260]: https://amplitude.atlassian.net/browse/AMP-108260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: autocapture.elementInteractions (visual labeler)

template.tpl
Jira: [AMP-111576](https://amplitude.atlassian.net/browse/AMP-111576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Should track file down events when url with params
[AMP-111576]: https://amplitude.atlassian.net/browse/AMP-111576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: should track file download when url has params

template.tpl
Jira: [AMP-115299]
"Identify Settings" section is shared by both "identify" and "group identify". However, it sticks with the word "user property" which causes confusion when comes to "group identify" with the expectation to be "group property". Previous version has already been released and the template only pulls `object.user_properties`. For backward compatibility, instead of pulling `object.group_properties`, we keep the template code and add a note there as group properties are just user properties for the group members. 
[AMP-115299]: https://amplitude.atlassian.net/browse/AMP-115299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add note for group properties

template.tpl
[AMP-119988](https://amplitude.atlassian.net/browse/AMP-119988)
Have an identify tag to unset:
Successfully unset
[AMP-119988]: https://amplitude.atlassian.net/browse/AMP-119988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: support identify.unset & bump to 2.11.10

template.tpl
3.17.1 is the same as 3.17.2. Skipping it and bump to 3.17.2
=> chore: bump WRAPPER_VERSION to 3.17.2
